# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: encryption-time2
version: '0.0.0'
github: "githubuser/encryption-time2"
license: MIT
author: "Author name here"
maintainer: "Author name here"
# synopsis: A new Haskeleton package.
# description: encryption-time2 is a new Haskeleton package.
# category: Other

default-extensions:
- OverloadedStrings

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  - cryptonite
  source-dirs: library

executables:
  encryption-time2:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - encryption-time2
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  encryption-time2-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - encryption-time2
    - criterion
    - cryptonite
    - bytestring
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -O2

tests:
  encryption-time2-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - encryption-time2
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
